// Generated by CIRCT unknown git version
module Example(	// <stdin>:3:10
  input        clock,	// <stdin>:4:11
               reset,	// <stdin>:5:11
               a,	// src/main/scala/Example.scala:4:19
               b,	// src/main/scala/Example.scala:4:19
               c,	// src/main/scala/Example.scala:4:19
               d,	// src/main/scala/Example.scala:5:19
               e,	// src/main/scala/Example.scala:5:19
               f,	// src/main/scala/Example.scala:5:19
  input  [7:0] foo,	// src/main/scala/Example.scala:6:20
               bar,	// src/main/scala/Example.scala:6:20
  output [7:0] out	// src/main/scala/Example.scala:7:15
);

  reg [7:0] myReg;	// src/main/scala/Example.scala:9:22
  always @(posedge clock) begin	// <stdin>:4:11
    if (reset)	// <stdin>:4:11
      myReg <= 8'h0;	// src/main/scala/Example.scala:9:22
    else if (d & e & f)	// src/main/scala/Example.scala:15:15
      myReg <= bar;	// src/main/scala/Example.scala:9:22
    else if (a & b & c)	// src/main/scala/Example.scala:12:15
      myReg <= foo;	// src/main/scala/Example.scala:9:22
  end // always @(posedge)
  assign out = myReg;	// <stdin>:3:10, src/main/scala/Example.scala:9:22
endmodule


// ----- 8< ----- FILE "metadata/tb_seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "metadata/seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "Example_firtool.conf" ----- 8< -----


