// Generated by CIRCT unknown git version
module Memory1R1WWriteFirst(	// <stdin>:3:10
  input         clock,	// <stdin>:4:11
                reset,	// <stdin>:5:11
  input  [4:0]  raddr,	// src/main/scala/Memory.scala:38:17
                waddr,	// src/main/scala/Memory.scala:41:17
  input  [63:0] wdata,	// src/main/scala/Memory.scala:42:17
  output [63:0] rdata	// src/main/scala/Memory.scala:39:17
);

  mem mem (	// src/main/scala/Memory.scala:44:24
    .R0_addr (raddr),
    .R0_clk  (clock),
    .W0_addr (waddr),
    .W0_clk  (clock),
    .W0_data (wdata),
    .R0_data (rdata)
  );
endmodule

module mem(	// src/main/scala/Memory.scala:44:24
  input  [4:0]  R0_addr,
  input         R0_clk,
  input  [4:0]  W0_addr,
  input         W0_clk,
  input  [63:0] W0_data,
  output [63:0] R0_data
);

  mem_ext mem_ext (	// src/main/scala/Memory.scala:44:24
    .R0_addr (R0_addr),
    .R0_en   (1'h1),
    .R0_clk  (R0_clk),
    .W0_addr (W0_addr),
    .W0_en   (1'h1),
    .W0_clk  (W0_clk),
    .W0_data (W0_data),
    .R0_data (R0_data)
  );
endmodule

// external module mem_ext


// ----- 8< ----- FILE "metadata/tb_seq_mems.json" ----- 8< -----

[
  {
    "module_name": "mem_ext",
    "depth": 32,
    "width": 64,
    "masked": false,
    "read": true,
    "write": true,
    "readwrite": false,
    "extra_ports": [],
    "hierarchy": [
      "Memory1R1WWriteFirst.mem.mem_ext"
    ]
  }
]

// ----- 8< ----- FILE "metadata/seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "Memory1R1WWriteFirst_firtool.conf" ----- 8< -----

name mem_ext depth 32 width 64 ports write,read
