// Generated by CIRCT unknown git version
// VCS coverage exclude_file
module mem_combMem(	// src/main/scala/Memory.scala:104:24
  input  [4:0]  R0_addr,
  input         R0_en,
                R0_clk,
  input  [4:0]  R1_addr,
  input         R1_en,
                R1_clk,
  input  [4:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [63:0] W0_data,
  input  [4:0]  W1_addr,
  input         W1_en,
                W1_clk,
  input  [63:0] W1_data,
  output [63:0] R0_data,
                R1_data
);

  reg [63:0] Memory[0:31];	// src/main/scala/Memory.scala:104:24
  reg        _GEN;	// src/main/scala/Memory.scala:104:24
  reg [4:0]  _GEN_0;	// src/main/scala/Memory.scala:104:24
  always @(posedge R0_clk) begin	// src/main/scala/Memory.scala:104:24
    _GEN <= R0_en;	// src/main/scala/Memory.scala:104:24
    _GEN_0 <= R0_addr;	// src/main/scala/Memory.scala:104:24
  end // always @(posedge)
  reg        _GEN_1;	// src/main/scala/Memory.scala:104:24
  reg [4:0]  _GEN_2;	// src/main/scala/Memory.scala:104:24
  always @(posedge R1_clk) begin	// src/main/scala/Memory.scala:104:24
    _GEN_1 <= R1_en;	// src/main/scala/Memory.scala:104:24
    _GEN_2 <= R1_addr;	// src/main/scala/Memory.scala:104:24
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/Memory.scala:104:24
    if (W0_en)	// src/main/scala/Memory.scala:104:24
      Memory[W0_addr] <= W0_data;	// src/main/scala/Memory.scala:104:24
    if (W1_en)	// src/main/scala/Memory.scala:104:24
      Memory[W1_addr] <= W1_data;	// src/main/scala/Memory.scala:104:24
  end // always @(posedge)
  assign R0_data = _GEN ? Memory[_GEN_0] : 64'bx;	// src/main/scala/Memory.scala:104:24
  assign R1_data = _GEN_1 ? Memory[_GEN_2] : 64'bx;	// src/main/scala/Memory.scala:104:24
endmodule

module Memory2R2W(	// <stdin>:3:10
  input         clock,	// <stdin>:4:11
                reset,	// <stdin>:5:11
  input  [4:0]  r1addr,	// src/main/scala/Memory.scala:94:18
                r2addr,	// src/main/scala/Memory.scala:96:18
                w1addr,	// src/main/scala/Memory.scala:99:18
  input  [63:0] w1data,	// src/main/scala/Memory.scala:100:18
  input  [4:0]  w2addr,	// src/main/scala/Memory.scala:101:18
  input  [63:0] w2data,	// src/main/scala/Memory.scala:102:18
  output [63:0] r1data,	// src/main/scala/Memory.scala:95:18
                r2data	// src/main/scala/Memory.scala:97:18
);

  mem_combMem mem_ext (	// src/main/scala/Memory.scala:104:24
    .R0_addr (r1addr),
    .R0_en   (1'h1),	// <stdin>:3:10
    .R0_clk  (clock),
    .R1_addr (r2addr),
    .R1_en   (1'h1),	// <stdin>:3:10
    .R1_clk  (clock),
    .W0_addr (w1addr),
    .W0_en   (1'h1),	// <stdin>:3:10
    .W0_clk  (clock),
    .W0_data (w1data),
    .W1_addr (w2addr),
    .W1_en   (1'h1),	// <stdin>:3:10
    .W1_clk  (clock),
    .W1_data (w2data),
    .R0_data (r1data),
    .R1_data (r2data)
  );
endmodule


// ----- 8< ----- FILE "metadata/tb_seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "metadata/seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "Memory2R2W_firtool.conf" ----- 8< -----


