// Generated by CIRCT unknown git version
// VCS coverage exclude_file
module mem_combMem(	// src/main/scala/Memory.scala:93:24
  input  [4:0]  RW0_addr,
  input         RW0_en,
                RW0_clk,
                RW0_wmode,
  input  [63:0] RW0_wdata,
  input  [4:0]  RW1_addr,
  input         RW1_en,
                RW1_clk,
                RW1_wmode,
  input  [63:0] RW1_wdata,
  output [63:0] RW0_rdata,
                RW1_rdata
);

  reg [63:0] Memory[0:31];	// src/main/scala/Memory.scala:93:24
  reg [4:0]  _GEN;	// src/main/scala/Memory.scala:93:24
  reg        _GEN_0;	// src/main/scala/Memory.scala:93:24
  reg        _GEN_1;	// src/main/scala/Memory.scala:93:24
  always @(posedge RW0_clk) begin	// src/main/scala/Memory.scala:93:24
    _GEN <= RW0_addr;	// src/main/scala/Memory.scala:93:24
    _GEN_0 <= RW0_en;	// src/main/scala/Memory.scala:93:24
    _GEN_1 <= RW0_wmode;	// src/main/scala/Memory.scala:93:24
    if (RW0_en & RW0_wmode)	// src/main/scala/Memory.scala:93:24
      Memory[RW0_addr] <= RW0_wdata;	// src/main/scala/Memory.scala:93:24
  end // always @(posedge)
  reg [4:0]  _GEN_2;	// src/main/scala/Memory.scala:93:24
  reg        _GEN_3;	// src/main/scala/Memory.scala:93:24
  reg        _GEN_4;	// src/main/scala/Memory.scala:93:24
  always @(posedge RW1_clk) begin	// src/main/scala/Memory.scala:93:24
    _GEN_2 <= RW1_addr;	// src/main/scala/Memory.scala:93:24
    _GEN_3 <= RW1_en;	// src/main/scala/Memory.scala:93:24
    _GEN_4 <= RW1_wmode;	// src/main/scala/Memory.scala:93:24
    if (RW1_en & RW1_wmode)	// src/main/scala/Memory.scala:93:24
      Memory[RW1_addr] <= RW1_wdata;	// src/main/scala/Memory.scala:93:24
  end // always @(posedge)
  assign RW0_rdata = _GEN_0 & ~_GEN_1 ? Memory[_GEN] : 64'bx;	// src/main/scala/Memory.scala:93:24
  assign RW1_rdata = _GEN_3 & ~_GEN_4 ? Memory[_GEN_2] : 64'bx;	// src/main/scala/Memory.scala:93:24
endmodule

module Memory2RW(	// <stdin>:3:10
  input         clock,	// <stdin>:4:11
                reset,	// <stdin>:5:11
  input  [4:0]  p1addr,	// src/main/scala/Memory.scala:83:18
  input  [63:0] p1wdata,	// src/main/scala/Memory.scala:85:19
  input         p1we,	// src/main/scala/Memory.scala:86:16
  input  [4:0]  p2addr,	// src/main/scala/Memory.scala:88:18
  input  [63:0] p2wdata,	// src/main/scala/Memory.scala:90:19
  input         p2we,	// src/main/scala/Memory.scala:91:16
  output [63:0] p1rdata,	// src/main/scala/Memory.scala:84:19
                p2rdata	// src/main/scala/Memory.scala:89:19
);

  mem_combMem mem_ext (	// src/main/scala/Memory.scala:93:24
    .RW0_addr  (p1addr),
    .RW0_en    (1'h1),	// <stdin>:3:10
    .RW0_clk   (clock),
    .RW0_wmode (p1we),
    .RW0_wdata (p1wdata),
    .RW1_addr  (p2addr),
    .RW1_en    (1'h1),	// <stdin>:3:10
    .RW1_clk   (clock),
    .RW1_wmode (p2we),
    .RW1_wdata (p2wdata),
    .RW0_rdata (p1rdata),
    .RW1_rdata (p2rdata)
  );
endmodule


// ----- 8< ----- FILE "metadata/tb_seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "metadata/seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "Memory2RW_firtool.conf" ----- 8< -----


