// Generated by CIRCT unknown git version
module MulAddRecFNToRaw_preMul(	// <stdin>:3:10
  input  [1:0]  io_op,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  input  [32:0] io_a,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_b,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_c,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output [23:0] io_mulAddA,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_mulAddB,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output [47:0] io_mulAddC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output        io_toPostMul_isSigNaNAny,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isNaNAOrB,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isInfA,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isZeroA,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isInfB,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isZeroB,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_signProd,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isNaNC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isInfC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_isZeroC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output [9:0]  io_toPostMul_sExpSum,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output        io_toPostMul_doSubMags,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
                io_toPostMul_CIsDominant,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output [4:0]  io_toPostMul_CDom_CAlignDist,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output [25:0] io_toPostMul_highAlignedSigC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
  output        io_toPostMul_bit0AlignedSigC	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:73:16
);

  wire        rawA_isNaN = (&(io_a[31:30])) & io_a[29];	// submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}
  wire        rawB_isNaN = (&(io_b[31:30])) & io_b[29];	// submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}
  wire        rawC_isNaN = (&(io_c[31:30])) & io_c[29];	// submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}
  wire        signProd = io_a[32] ^ io_b[32] ^ io_op[1];	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:96:{42,49}, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:59:25
  wire [10:0] _sExpAlignedProd_T_2 = {2'h0, io_a[31:23]} + {2'h0, io_b[31:23]} - 11'hE5;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:99:{19,32}, :121:30, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21
  wire        doSubMags = signProd ^ io_c[32] ^ io_op[0];	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:96:42, :101:{42,49}, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:59:25
  wire [10:0] _sNatCAlignDist_T_1 = _sExpAlignedProd_T_2 - {2'h0, io_c[31:23]};	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:99:32, :105:42, :121:30, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21
  wire        isMinCAlign =
    ~(|(io_a[31:29])) | ~(|(io_b[31:29])) | $signed(_sNatCAlignDist_T_1) < 11'sh0;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:105:42, :107:{50,69}, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}
  wire        CIsDominant =
    (|(io_c[31:29])) & (isMinCAlign | _sNatCAlignDist_T_1[9:0] < 10'h19);	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:105:42, :106:42, :107:50, :109:{23,39,60}, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}
  wire [6:0]  CAlignDist =
    isMinCAlign
      ? 7'h0
      : _sNatCAlignDist_T_1[9:0] < 10'h4A ? _sNatCAlignDist_T_1[6:0] : 7'h4A;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:105:42, :106:42, :107:50, :111:12, :113:{16,34}, :114:33
  wire [77:0] mainAlignedSigC =
    $signed($signed({doSubMags
                       ? {1'h1, ~(|(io_c[31:29])), ~(io_c[22:0])}
                       : {1'h0, |(io_c[31:29]), io_c[22:0]},
                     {53{doSubMags}}}) >>> CAlignDist);	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:101:42, :107:69, :111:12, :119:{13,25,46,53,100}, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:{44,49}
  wire [32:0] reduced4CExtra_shift = $signed(33'sh100000000 >>> CAlignDist[6:2]);	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:111:12, :123:28, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:76:56
  wire [5:0]  _GEN =
    {|(io_c[21:18]),
     |(io_c[17:14]),
     |(io_c[13:10]),
     |(io_c[9:6]),
     |(io_c[5:2]),
     |(io_c[1:0])}
    & {reduced4CExtra_shift[14],
       reduced4CExtra_shift[15],
       reduced4CExtra_shift[16],
       reduced4CExtra_shift[17],
       reduced4CExtra_shift[18],
       reduced4CExtra_shift[19]};	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:121:68, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:76:56, :77:20, :78:22, :120:{33,54}, :124:20
  assign io_mulAddA = {|(io_a[31:29]), io_a[22:0]};	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:140:16, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:49
  assign io_mulAddB = {|(io_b[31:29]), io_b[22:0]};	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:141:16, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:49
  assign io_mulAddC = mainAlignedSigC[50:3];	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:119:100, :142:30
  assign io_toPostMul_isSigNaNAny =
    rawA_isNaN & ~(io_a[22]) | rawB_isNaN & ~(io_b[22]) | rawC_isNaN & ~(io_c[22]);	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:145:58, submodules/berkeley-hardfloat/src/main/scala/common.scala:82:{46,49,56}, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:56:33
  assign io_toPostMul_isNaNAOrB = rawA_isNaN | rawB_isNaN;	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:147:42, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:56:33
  assign io_toPostMul_isInfA = (&(io_a[31:30])) & ~(io_a[29]);	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
  assign io_toPostMul_isZeroA = ~(|(io_a[31:29]));	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}
  assign io_toPostMul_isInfB = (&(io_b[31:30])) & ~(io_b[29]);	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
  assign io_toPostMul_isZeroB = ~(|(io_b[31:29]));	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}
  assign io_toPostMul_signProd = signProd;	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:96:42
  assign io_toPostMul_isNaNC = rawC_isNaN;	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:56:33
  assign io_toPostMul_isInfC = (&(io_c[31:30])) & ~(io_c[29]);	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}
  assign io_toPostMul_isZeroC = ~(|(io_c[31:29]));	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}
  assign io_toPostMul_sExpSum =
    CIsDominant ? {1'h0, io_c[31:23]} : _sExpAlignedProd_T_2[9:0] - 10'h18;	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:99:32, :107:69, :109:23, :157:{12,53}, submodules/berkeley-hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21
  assign io_toPostMul_doSubMags = doSubMags;	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:101:42
  assign io_toPostMul_CIsDominant = CIsDominant;	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:109:23
  assign io_toPostMul_CDom_CAlignDist = CAlignDist[4:0];	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:111:12, :160:47
  assign io_toPostMul_highAlignedSigC = mainAlignedSigC[76:51];	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:119:100, :162:20
  assign io_toPostMul_bit0AlignedSigC =
    doSubMags
      ? (&(mainAlignedSigC[2:0])) & ~(|_GEN)
      : (|(mainAlignedSigC[2:0])) | (|_GEN);	// <stdin>:3:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:101:42, :119:100, :121:68, :129:11, :132:16, :133:{32,39,44,47}, :134:{39,44}
endmodule

module MulAddRecFNToRaw_postMul(	// <stdin>:207:10
  input         io_fromPreMul_isSigNaNAny,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isNaNAOrB,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isInfA,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isZeroA,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isInfB,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isZeroB,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_signProd,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isNaNC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isInfC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_isZeroC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  input  [9:0]  io_fromPreMul_sExpSum,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  input         io_fromPreMul_doSubMags,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_fromPreMul_CIsDominant,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  input  [4:0]  io_fromPreMul_CDom_CAlignDist,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  input  [25:0] io_fromPreMul_highAlignedSigC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  input         io_fromPreMul_bit0AlignedSigC,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  input  [48:0] io_mulAddResult,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  input  [2:0]  io_roundingMode,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  output        io_invalidExc,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_rawOut_isNaN,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_rawOut_isInf,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_rawOut_isZero,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
                io_rawOut_sign,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  output [9:0]  io_rawOut_sExp,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
  output [26:0] io_rawOut_sig	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:170:16
);

  wire         roundingMode_min = io_roundingMode == 3'h2;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:184:45
  wire         opSignC = io_fromPreMul_signProd ^ io_fromPreMul_doSubMags;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:188:42
  wire [25:0]  _sigSum_T_3 =
    io_mulAddResult[48]
      ? io_fromPreMul_highAlignedSigC + 26'h1
      : io_fromPreMul_highAlignedSigC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:190:{16,32}, :191:47
  wire [49:0]  CDom_absSigSum =
    io_fromPreMul_doSubMags
      ? ~{_sigSum_T_3, io_mulAddResult[47:24]}
      : {1'h0,
         io_fromPreMul_highAlignedSigC[25:24],
         _sigSum_T_3[23:0],
         io_mulAddResult[47:25]};	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:190:16, :203:12, :204:{13,20}, :205:22, :207:{46,71}, :208:23
  wire [80:0]  _CDom_mainSig_T = {31'h0, CDom_absSigSum} << io_fromPreMul_CDom_CAlignDist;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:203:12, :217:24
  wire [8:0]   CDom_reduced4SigExtra_shift =
    $signed(9'sh100 >>> ~(io_fromPreMul_CDom_CAlignDist[4:2]));	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:221:51, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:52:21, :76:56
  wire [50:0]  notCDom_absSigSum =
    _sigSum_T_3[2]
      ? ~{_sigSum_T_3[1:0], io_mulAddResult[47:0], io_fromPreMul_bit0AlignedSigC}
      : {_sigSum_T_3[1:0], io_mulAddResult[47:0], io_fromPreMul_bit0AlignedSigC}
        + {50'h0, io_fromPreMul_doSubMags};	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:190:16, :194:28, :230:36, :232:12, :233:{13,20}, :234:41
  wire [4:0]   notCDom_normDistReduced2 =
    notCDom_absSigSum[50]
      ? 5'h0
      : (|(notCDom_absSigSum[49:48]))
          ? 5'h1
          : (|(notCDom_absSigSum[47:46]))
              ? 5'h2
              : (|(notCDom_absSigSum[45:44]))
                  ? 5'h3
                  : (|(notCDom_absSigSum[43:42]))
                      ? 5'h4
                      : (|(notCDom_absSigSum[41:40]))
                          ? 5'h5
                          : (|(notCDom_absSigSum[39:38]))
                              ? 5'h6
                              : (|(notCDom_absSigSum[37:36]))
                                  ? 5'h7
                                  : (|(notCDom_absSigSum[35:34]))
                                      ? 5'h8
                                      : (|(notCDom_absSigSum[33:32]))
                                          ? 5'h9
                                          : (|(notCDom_absSigSum[31:30]))
                                              ? 5'hA
                                              : (|(notCDom_absSigSum[29:28]))
                                                  ? 5'hB
                                                  : (|(notCDom_absSigSum[27:26]))
                                                      ? 5'hC
                                                      : (|(notCDom_absSigSum[25:24]))
                                                          ? 5'hD
                                                          : (|(notCDom_absSigSum[23:22]))
                                                              ? 5'hE
                                                              : (|(notCDom_absSigSum[21:20]))
                                                                  ? 5'hF
                                                                  : (|(notCDom_absSigSum[19:18]))
                                                                      ? 5'h10
                                                                      : (|(notCDom_absSigSum[17:16]))
                                                                          ? 5'h11
                                                                          : (|(notCDom_absSigSum[15:14]))
                                                                              ? 5'h12
                                                                              : (|(notCDom_absSigSum[13:12]))
                                                                                  ? 5'h13
                                                                                  : (|(notCDom_absSigSum[11:10]))
                                                                                      ? 5'h14
                                                                                      : (|(notCDom_absSigSum[9:8]))
                                                                                          ? 5'h15
                                                                                          : (|(notCDom_absSigSum[7:6]))
                                                                                              ? 5'h16
                                                                                              : (|(notCDom_absSigSum[5:4]))
                                                                                                  ? 5'h17
                                                                                                  : {4'hC,
                                                                                                     ~(|(notCDom_absSigSum[3:2]))};	// src/main/scala/chisel3/util/Mux.scala:50:70, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:232:12, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:103:{33,54}, :106:15
  wire [113:0] _notCDom_mainSig_T =
    {63'h0, notCDom_absSigSum} << {108'h0, notCDom_normDistReduced2, 1'h0};	// src/main/scala/chisel3/util/Mux.scala:50:70, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:205:22, :232:12, :241:27
  wire [16:0]  notCDom_reduced4SigExtra_shift =
    $signed(17'sh10000 >>> ~(notCDom_normDistReduced2[4:1]));	// src/main/scala/chisel3/util/Mux.scala:50:70, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:246:46, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:52:21, :76:56
  wire         notCDom_completeCancellation = _notCDom_mainSig_T[51:50] == 2'h0;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:241:27, :253:{21,50}, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:103:54
  wire         notNaN_isInfProd = io_fromPreMul_isInfA | io_fromPreMul_isInfB;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:262:49
  wire         notNaN_isInfOut = notNaN_isInfProd | io_fromPreMul_isInfC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:262:49, :263:44
  wire         notNaN_addZeros =
    (io_fromPreMul_isZeroA | io_fromPreMul_isZeroB) & io_fromPreMul_isZeroC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:265:{32,58}
  assign io_invalidExc =
    io_fromPreMul_isSigNaNAny | io_fromPreMul_isInfA & io_fromPreMul_isZeroB
    | io_fromPreMul_isZeroA & io_fromPreMul_isInfB | ~io_fromPreMul_isNaNAOrB
    & notNaN_isInfProd & io_fromPreMul_isInfC & io_fromPreMul_doSubMags;	// <stdin>:207:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:262:49, :270:31, :271:{32,57}, :272:10, :274:35
  assign io_rawOut_isNaN = io_fromPreMul_isNaNAOrB | io_fromPreMul_isNaNC;	// <stdin>:207:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:276:48
  assign io_rawOut_isInf = notNaN_isInfOut;	// <stdin>:207:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:263:44
  assign io_rawOut_isZero =
    notNaN_addZeros | ~io_fromPreMul_CIsDominant & notCDom_completeCancellation;	// <stdin>:207:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:253:50, :265:58, :280:25, :281:{14,42}
  assign io_rawOut_sign =
    notNaN_isInfProd & io_fromPreMul_signProd | io_fromPreMul_isInfC & opSignC
    | notNaN_addZeros & ~roundingMode_min & io_fromPreMul_signProd & opSignC
    | notNaN_addZeros & roundingMode_min & (io_fromPreMul_signProd | opSignC)
    | ~notNaN_isInfOut & ~notNaN_addZeros
    & (io_fromPreMul_CIsDominant
         ? opSignC
         : notCDom_completeCancellation
             ? roundingMode_min
             : io_fromPreMul_signProd ^ _sigSum_T_3[2]);	// <stdin>:207:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:184:45, :188:42, :190:16, :230:36, :253:50, :255:12, :257:36, :262:49, :263:44, :265:58, :283:27, :284:31, :285:29, :286:36, :287:46, :288:{37,50}, :289:{10,31,49}, :290:17
  assign io_rawOut_sExp =
    io_fromPreMul_CIsDominant
      ? io_fromPreMul_sExpSum - {9'h0, io_fromPreMul_doSubMags}
      : io_fromPreMul_sExpSum - {4'h0, notCDom_normDistReduced2, 1'h0};	// <stdin>:207:10, src/main/scala/chisel3/util/Mux.scala:50:70, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:201:43, :205:22, :239:46, :291:26, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:120:54
  assign io_rawOut_sig =
    io_fromPreMul_CIsDominant
      ? {_CDom_mainSig_T[49:24],
         (|(_CDom_mainSig_T[23:21]))
           | (|({|(CDom_absSigSum[20:17]),
                 |(CDom_absSigSum[16:13]),
                 |(CDom_absSigSum[12:9]),
                 |(CDom_absSigSum[8:5]),
                 |(CDom_absSigSum[4:1]),
                 CDom_absSigSum[0]}
                & {CDom_reduced4SigExtra_shift[1],
                   CDom_reduced4SigExtra_shift[2],
                   CDom_reduced4SigExtra_shift[3],
                   CDom_reduced4SigExtra_shift[4],
                   CDom_reduced4SigExtra_shift[5],
                   CDom_reduced4SigExtra_shift[6]}))
           | (io_fromPreMul_doSubMags
                ? io_mulAddResult[23:0] != 24'hFFFFFF
                : (|(io_mulAddResult[24:0])))}
      : {_notCDom_mainSig_T[51:26],
         (|(_notCDom_mainSig_T[25:23]))
           | (|({|{|(notCDom_absSigSum[23:22]), |(notCDom_absSigSum[21:20])},
                 |{|(notCDom_absSigSum[19:18]), |(notCDom_absSigSum[17:16])},
                 |{|(notCDom_absSigSum[15:14]), |(notCDom_absSigSum[13:12])},
                 |{|(notCDom_absSigSum[11:10]), |(notCDom_absSigSum[9:8])},
                 |{|(notCDom_absSigSum[7:6]), |(notCDom_absSigSum[5:4])},
                 |{|(notCDom_absSigSum[3:2]), |(notCDom_absSigSum[1:0])}}
                & {notCDom_reduced4SigExtra_shift[1],
                   notCDom_reduced4SigExtra_shift[2],
                   notCDom_reduced4SigExtra_shift[3],
                   notCDom_reduced4SigExtra_shift[4],
                   notCDom_reduced4SigExtra_shift[5],
                   notCDom_reduced4SigExtra_shift[6]}))};	// <stdin>:207:10, submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:203:12, :212:12, :213:{14,21,36}, :214:{19,37}, :217:{24,56}, :220:72, :221:73, :223:{12,25}, :224:{25,32,61}, :232:12, :241:{27,50}, :245:{39,78}, :247:11, :249:{12,28}, :250:{28,35,39}, :292:25, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:76:56, :77:20, :78:22, :103:{33,54}, :107:20, :120:{33,54}, :124:20
endmodule

module RoundAnyRawFNToRecFN(	// <stdin>:570:10
  input         io_invalidExc,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
                io_in_isNaN,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
                io_in_isInf,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
                io_in_isZero,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
                io_in_sign,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
  input  [9:0]  io_in_sExp,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
  input  [26:0] io_in_sig,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
  input  [2:0]  io_roundingMode,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
  input         io_detectTininess,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
  output [32:0] io_out,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
  output [4:0]  io_exceptionFlags	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16
);

  wire        roundingMode_near_even = io_roundingMode == 3'h0;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:89:53, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:62:24
  wire        roundingMode_odd = io_roundingMode == 3'h6;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:94:53
  wire        roundMagUp =
    io_roundingMode == 3'h2 & io_in_sign | io_roundingMode == 3'h3 & ~io_in_sign;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:91:53, :92:53, :97:{27,42,63,66}, :195:50
  wire [8:0]  _roundMask_T_1 = ~(io_in_sExp[8:0]);	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:155:37, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:52:21
  wire [64:0] _GEN = {59'h0, _roundMask_T_1[5:0]};	// submodules/berkeley-hardfloat/src/main/scala/primitives.scala:52:21, :59:26, :76:56
  wire [64:0] roundMask_shift = $signed(65'sh10000000000000000 >>> _GEN);	// submodules/berkeley-hardfloat/src/main/scala/primitives.scala:76:56
  wire [64:0] roundMask_shift_1 = $signed(65'sh10000000000000000 >>> _GEN);	// submodules/berkeley-hardfloat/src/main/scala/primitives.scala:76:56
  wire [24:0] _roundMask_T_74 =
    (_roundMask_T_1[8]
       ? (_roundMask_T_1[7]
            ? {~(_roundMask_T_1[6]
                   ? 22'h0
                   : ~{roundMask_shift[42],
                       roundMask_shift[43],
                       roundMask_shift[44],
                       roundMask_shift[45],
                       roundMask_shift[46],
                       roundMask_shift[47],
                       roundMask_shift[48],
                       roundMask_shift[49],
                       roundMask_shift[50],
                       roundMask_shift[51],
                       roundMask_shift[52],
                       roundMask_shift[53],
                       roundMask_shift[54],
                       roundMask_shift[55],
                       roundMask_shift[56],
                       roundMask_shift[57],
                       roundMask_shift[58],
                       roundMask_shift[59],
                       roundMask_shift[60],
                       roundMask_shift[61],
                       roundMask_shift[62],
                       roundMask_shift[63]}),
               3'h7}
            : {22'h0,
               _roundMask_T_1[6]
                 ? {roundMask_shift_1[0], roundMask_shift_1[1], roundMask_shift_1[2]}
                 : 3'h0})
       : 25'h0) | {24'h0, io_in_sig[26]};	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:119:57, :158:23, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:52:21, :58:25, :59:26, :62:24, :67:24, :68:58, :73:{17,21,32}, :76:56, :77:20, :78:22
  wire [25:0] _GEN_0 = {_roundMask_T_74, 1'h1};	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:158:{23,42}, :173:49
  wire [25:0] _roundedSig_T_14 = {1'h1, ~_roundMask_T_74} & _GEN_0;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:158:{23,42}, :161:53, :162:{28,46}, :173:49
  wire [25:0] _GEN_1 = io_in_sig[26:1] & _roundedSig_T_14;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16, :162:46, :163:40
  wire [25:0] _GEN_2 = io_in_sig[25:0] & _GEN_0;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16, :158:42, :164:42
  wire        anyRound = (|_GEN_1) | (|_GEN_2);	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:163:{40,56}, :164:{42,62}, :165:36
  wire        _overflow_roundMagUp_T = roundingMode_near_even | io_roundingMode == 3'h4;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:89:53, :93:53, :168:38
  wire [25:0] roundedSig =
    _overflow_roundMagUp_T & (|_GEN_1) | roundMagUp & anyRound
      ? {1'h0, io_in_sig[26:2] | _roundMask_T_74} + 26'h1
        & ~(roundingMode_near_even & (|_GEN_1) & ~(|_GEN_2)
              ? {_roundMask_T_74, 1'h1}
              : 26'h0)
      : {1'h0, io_in_sig[26:2] & ~_roundMask_T_74}
        | (roundingMode_odd & anyRound ? _roundedSig_T_14 : 26'h0);	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16, :89:53, :94:53, :97:42, :158:23, :162:{28,46}, :163:{40,56}, :164:{42,62}, :165:36, :168:{38,67}, :169:31, :170:29, :172:16, :173:{32,49,57}, :174:{21,25,64}, :175:30, :176:35, :179:{30,47}, :180:{24,42}
  wire [10:0] sRoundedExp = {io_in_sExp[9], io_in_sExp} + {9'h0, roundedSig[25:24]};	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:172:16, :184:{40,54}, :252:18
  wire        common_totalUnderflow = $signed(sRoundedExp) < 11'sh6B;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:184:40, :199:31
  wire        isNaNOut = io_invalidExc | io_in_isNaN;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:234:34
  wire        commonCase = ~isNaNOut & ~io_in_isInf & ~io_in_isZero;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:234:34, :236:{22,36,61,64}
  wire        overflow = commonCase & $signed(sRoundedExp[10:7]) > 4'sh2;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:184:40, :195:{30,50}, :236:61, :237:32
  wire        overflow_roundMagUp = _overflow_roundMagUp_T | roundMagUp;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:97:42, :168:38, :242:60
  wire        pegMinNonzeroMagOut =
    commonCase & common_totalUnderflow & (roundMagUp | roundingMode_odd);	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:94:53, :97:42, :199:31, :236:61, :244:{45,60}
  wire        pegMaxFiniteMagOut = overflow & ~overflow_roundMagUp;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:237:32, :242:60, :245:{39,42}
  wire        notNaN_isInfOut = io_in_isInf | overflow & overflow_roundMagUp;	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:237:32, :242:60, :247:{32,45}
  assign io_out =
    {~isNaNOut & io_in_sign,
     sRoundedExp[8:0] & ~(io_in_isZero | common_totalUnderflow ? 9'h1C0 : 9'h0)
       & ~(pegMinNonzeroMagOut ? 9'h194 : 9'h0) & {1'h1, ~pegMaxFiniteMagOut, 7'h7F}
       & {2'h3, ~notNaN_isInfOut, 6'h3F} | (pegMinNonzeroMagOut ? 9'h6B : 9'h0)
       | (pegMaxFiniteMagOut ? 9'h17F : 9'h0) | (notNaN_isInfOut ? 9'h180 : 9'h0)
       | (isNaNOut ? 9'h1C0 : 9'h0),
     (isNaNOut | io_in_isZero | common_totalUnderflow
        ? {isNaNOut, 22'h0}
        : io_in_sig[26] ? roundedSig[23:1] : roundedSig[22:0])
       | {23{pegMaxFiniteMagOut}}};	// <stdin>:570:10, submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:119:57, :158:42, :172:16, :173:49, :184:40, :186:37, :188:16, :189:27, :190:27, :199:31, :234:34, :244:45, :245:39, :247:32, :249:22, :252:{14,18,32}, :256:{14,18}, :257:19, :260:{14,18}, :263:17, :264:{14,18}, :268:16, :272:16, :276:{16,73}, :277:16, :279:{12,38}, :280:16, :282:11, :283:13, :285:33, submodules/berkeley-hardfloat/src/main/scala/primitives.scala:73:21
  assign io_exceptionFlags =
    {io_invalidExc,
     1'h0,
     overflow,
     commonCase
       & (common_totalUnderflow | anyRound & io_in_sExp[9:8] != 2'h1
          & (io_in_sig[26] ? _roundMask_T_74[1] : _roundMask_T_74[0])
          & ~(io_detectTininess
              & ~(io_in_sig[26] ? _roundMask_T_74[2] : _roundMask_T_74[1])
              & (io_in_sig[26] ? roundedSig[25] : roundedSig[24]) & (|_GEN_1)
              & (_overflow_roundMagUp_T & (io_in_sig[26] ? io_in_sig[2] : io_in_sig[1])
                 | roundMagUp & (io_in_sig[26] & io_in_sig[2] | (|(io_in_sig[1:0])))))),
     overflow | commonCase & (common_totalUnderflow | anyRound)};	// <stdin>:570:10, submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:57:16, :97:42, :119:57, :158:23, :163:{40,56}, :165:36, :168:38, :172:16, :199:31, :202:{16,45,61}, :204:{30,49,63,70}, :206:67, :207:46, :208:29, :210:16, :211:27, :212:27, :216:40, :219:{49,64}, :220:{30,57,71,76}, :221:27, :222:{34,39}, :223:49, :226:60, :229:49, :236:61, :237:32, :238:32, :239:{28,43}, :287:66
endmodule

module RoundRawFNToRecFN(	// <stdin>:818:10
  input         io_invalidExc,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
                io_in_isNaN,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
                io_in_isInf,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
                io_in_isZero,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
                io_in_sign,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
  input  [9:0]  io_in_sExp,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
  input  [26:0] io_in_sig,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
  input  [2:0]  io_roundingMode,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
  input         io_detectTininess,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
  output [32:0] io_out,	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
  output [4:0]  io_exceptionFlags	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:297:16
);

  RoundAnyRawFNToRecFN roundAnyRawFNToRecFN (	// submodules/berkeley-hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:308:15
    .io_invalidExc     (io_invalidExc),
    .io_in_isNaN       (io_in_isNaN),
    .io_in_isInf       (io_in_isInf),
    .io_in_isZero      (io_in_isZero),
    .io_in_sign        (io_in_sign),
    .io_in_sExp        (io_in_sExp),
    .io_in_sig         (io_in_sig),
    .io_roundingMode   (io_roundingMode),
    .io_detectTininess (io_detectTininess),
    .io_out            (io_out),
    .io_exceptionFlags (io_exceptionFlags)
  );
endmodule

module MulAddRecFN(	// <stdin>:835:10
  input  [1:0]  io_op,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
  input  [32:0] io_a,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
                io_b,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
                io_c,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
  input  [2:0]  io_roundingMode,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
  input         io_detectTininess,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
  output [32:0] io_out,	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
  output [4:0]  io_exceptionFlags	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:300:16
);

  wire        _mulAddRecFNToRaw_postMul_io_invalidExc;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
  wire        _mulAddRecFNToRaw_postMul_io_rawOut_isNaN;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
  wire        _mulAddRecFNToRaw_postMul_io_rawOut_isInf;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
  wire        _mulAddRecFNToRaw_postMul_io_rawOut_isZero;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
  wire        _mulAddRecFNToRaw_postMul_io_rawOut_sign;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
  wire [9:0]  _mulAddRecFNToRaw_postMul_io_rawOut_sExp;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
  wire [26:0] _mulAddRecFNToRaw_postMul_io_rawOut_sig;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
  wire [23:0] _mulAddRecFNToRaw_preMul_io_mulAddA;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire [23:0] _mulAddRecFNToRaw_preMul_io_mulAddB;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire [47:0] _mulAddRecFNToRaw_preMul_io_mulAddC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isSigNaNAny;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isNaNAOrB;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isInfA;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroA;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isInfB;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroB;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_signProd;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isNaNC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isInfC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_isZeroC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire [9:0]  _mulAddRecFNToRaw_preMul_io_toPostMul_sExpSum;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_doSubMags;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_CIsDominant;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire [4:0]  _mulAddRecFNToRaw_preMul_io_toPostMul_CDom_CAlignDist;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire [25:0] _mulAddRecFNToRaw_preMul_io_toPostMul_highAlignedSigC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  wire        _mulAddRecFNToRaw_preMul_io_toPostMul_bit0AlignedSigC;	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
  MulAddRecFNToRaw_preMul mulAddRecFNToRaw_preMul (	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_op                        (io_op),
    .io_a                         (io_a),
    .io_b                         (io_b),
    .io_c                         (io_c),
    .io_mulAddA                   (_mulAddRecFNToRaw_preMul_io_mulAddA),
    .io_mulAddB                   (_mulAddRecFNToRaw_preMul_io_mulAddB),
    .io_mulAddC                   (_mulAddRecFNToRaw_preMul_io_mulAddC),
    .io_toPostMul_isSigNaNAny     (_mulAddRecFNToRaw_preMul_io_toPostMul_isSigNaNAny),
    .io_toPostMul_isNaNAOrB       (_mulAddRecFNToRaw_preMul_io_toPostMul_isNaNAOrB),
    .io_toPostMul_isInfA          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfA),
    .io_toPostMul_isZeroA         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroA),
    .io_toPostMul_isInfB          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfB),
    .io_toPostMul_isZeroB         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroB),
    .io_toPostMul_signProd        (_mulAddRecFNToRaw_preMul_io_toPostMul_signProd),
    .io_toPostMul_isNaNC          (_mulAddRecFNToRaw_preMul_io_toPostMul_isNaNC),
    .io_toPostMul_isInfC          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfC),
    .io_toPostMul_isZeroC         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroC),
    .io_toPostMul_sExpSum         (_mulAddRecFNToRaw_preMul_io_toPostMul_sExpSum),
    .io_toPostMul_doSubMags       (_mulAddRecFNToRaw_preMul_io_toPostMul_doSubMags),
    .io_toPostMul_CIsDominant     (_mulAddRecFNToRaw_preMul_io_toPostMul_CIsDominant),
    .io_toPostMul_CDom_CAlignDist (_mulAddRecFNToRaw_preMul_io_toPostMul_CDom_CAlignDist),
    .io_toPostMul_highAlignedSigC (_mulAddRecFNToRaw_preMul_io_toPostMul_highAlignedSigC),
    .io_toPostMul_bit0AlignedSigC (_mulAddRecFNToRaw_preMul_io_toPostMul_bit0AlignedSigC)
  );
  MulAddRecFNToRaw_postMul mulAddRecFNToRaw_postMul (	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_fromPreMul_isSigNaNAny     (_mulAddRecFNToRaw_preMul_io_toPostMul_isSigNaNAny),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isNaNAOrB       (_mulAddRecFNToRaw_preMul_io_toPostMul_isNaNAOrB),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isInfA          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfA),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isZeroA         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroA),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isInfB          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfB),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isZeroB         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroB),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_signProd        (_mulAddRecFNToRaw_preMul_io_toPostMul_signProd),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isNaNC          (_mulAddRecFNToRaw_preMul_io_toPostMul_isNaNC),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isInfC          (_mulAddRecFNToRaw_preMul_io_toPostMul_isInfC),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_isZeroC         (_mulAddRecFNToRaw_preMul_io_toPostMul_isZeroC),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_sExpSum         (_mulAddRecFNToRaw_preMul_io_toPostMul_sExpSum),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_doSubMags       (_mulAddRecFNToRaw_preMul_io_toPostMul_doSubMags),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_CIsDominant     (_mulAddRecFNToRaw_preMul_io_toPostMul_CIsDominant),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_CDom_CAlignDist
      (_mulAddRecFNToRaw_preMul_io_toPostMul_CDom_CAlignDist),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_highAlignedSigC
      (_mulAddRecFNToRaw_preMul_io_toPostMul_highAlignedSigC),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_fromPreMul_bit0AlignedSigC
      (_mulAddRecFNToRaw_preMul_io_toPostMul_bit0AlignedSigC),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15
    .io_mulAddResult
      ({1'h0,
        {24'h0, _mulAddRecFNToRaw_preMul_io_mulAddA}
          * {24'h0, _mulAddRecFNToRaw_preMul_io_mulAddB}}
       + {1'h0, _mulAddRecFNToRaw_preMul_io_mulAddC}),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:314:15, :324:45, :325:50
    .io_roundingMode               (io_roundingMode),
    .io_invalidExc                 (_mulAddRecFNToRaw_postMul_io_invalidExc),
    .io_rawOut_isNaN               (_mulAddRecFNToRaw_postMul_io_rawOut_isNaN),
    .io_rawOut_isInf               (_mulAddRecFNToRaw_postMul_io_rawOut_isInf),
    .io_rawOut_isZero              (_mulAddRecFNToRaw_postMul_io_rawOut_isZero),
    .io_rawOut_sign                (_mulAddRecFNToRaw_postMul_io_rawOut_sign),
    .io_rawOut_sExp                (_mulAddRecFNToRaw_postMul_io_rawOut_sExp),
    .io_rawOut_sig                 (_mulAddRecFNToRaw_postMul_io_rawOut_sig)
  );
  RoundRawFNToRecFN roundRawFNToRecFN (	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:336:15
    .io_invalidExc     (_mulAddRecFNToRaw_postMul_io_invalidExc),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_in_isNaN       (_mulAddRecFNToRaw_postMul_io_rawOut_isNaN),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_in_isInf       (_mulAddRecFNToRaw_postMul_io_rawOut_isInf),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_in_isZero      (_mulAddRecFNToRaw_postMul_io_rawOut_isZero),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_in_sign        (_mulAddRecFNToRaw_postMul_io_rawOut_sign),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_in_sExp        (_mulAddRecFNToRaw_postMul_io_rawOut_sExp),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_in_sig         (_mulAddRecFNToRaw_postMul_io_rawOut_sig),	// submodules/berkeley-hardfloat/src/main/scala/MulAddRecFN.scala:316:15
    .io_roundingMode   (io_roundingMode),
    .io_detectTininess (io_detectTininess),
    .io_out            (io_out),
    .io_exceptionFlags (io_exceptionFlags)
  );
endmodule


// ----- 8< ----- FILE "metadata/tb_seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "metadata/seq_mems.json" ----- 8< -----

[]

// ----- 8< ----- FILE "MulAddRecFN_firtool.conf" ----- 8< -----


